# Generated by Django 5.2.14 on 2026-06-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_my_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='my_model',
        ),
    ]
