# Generated by Django 5.2.14 on 2026-06-19 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_alter_model_glbfacefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='avaterfile',
        ),
        migrations.AddField(
            model_name='model',
            name='avatarfile',
            field=models.FileField(blank=True, null=True, upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
        migrations.AlterField(
            model_name='model',
            name='is_type',
            field=models.CharField(choices=[('avaturn', 'Avaturn'), ('other', 'その他')], max_length=100),
        ),
    ]
