# Generated by Django 5.2.14 on 2026-06-07 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ネームタグ')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_private', models.BooleanField(default=False)),
                ('is_type', models.CharField(choices=[('avatern', 'Avatern'), ('other', 'その他')], max_length=100)),
                ('glbfile', models.FileField(upload_to='glb/')),
                ('avaterfile', models.FileField(blank=True, null=True, upload_to='avater/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Model',
            },
        ),
    ]
