# Generated by Django 5.2.14 on 2026-06-13 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='glbfacefile',
            field=models.ImageField(blank=True, null=True, upload_to='glbface/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='avaterfile',
            field=models.FileField(blank=True, null=True, upload_to='avater/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
        migrations.AlterField(
            model_name='model',
            name='glbfile',
            field=models.FileField(upload_to='glb/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb'])]),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ネームタグ'),
        ),
    ]
