# Generated by Django 5.2.14 on 2026-06-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_model_glbfacefile_alter_model_avaterfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='glbfacefile',
            field=models.ImageField(upload_to='glbfacefile/'),
        ),
    ]
